//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public long ID { get; set; }
        public long RoleID { get; set; }
        public string ParentID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string IC { get; set; }
        public string RID { get; set; }
        public string Address { get; set; }
        public Nullable<int> Epoint { get; set; }
        public Nullable<int> Rpoint { get; set; }
        public Nullable<int> BonusStar { get; set; }
        public Nullable<long> StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual Ref_Role Ref_Role { get; set; }
        public virtual Ref_Status Ref_Status { get; set; }
    }
}
